### ISSUE TITLE
Link?

### ISSUE THREAD

**Issue by RDIL** [KodaxBot/Kodax#1]
What’s the invite link?  I would like to try it out.

**Comment by KodingDev** [comment]
Hi,

The bot is currently in very early development, so I haven't set up 24/7 hosting as of yet.
However, you can compile the bot and run it yourself if you wish to test it out.
I will be adding some wiki pages for a tutorial on how to do this soon.

Thanks,
Koding

**Comment by KodingDev** [comment]
Hi again,

If you are looking to build Kodax, check out the wiki [here](https://github.com/KodaxBot/Kodax/wiki).
I have currently only added a tutorial for Linux, however it should be pretty simple to get it to work for windows for testing.
I appreciate your interest in the project.

Thanks,
Koding

**Comment by RDIL** [comment]
Thanks!
